// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProject.Data;

namespace TestProject.Migrations
{
    [DbContext(typeof(TestProjectContext))]
    partial class TestProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestProject.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            Number = 5
                        });
                });

            modelBuilder.Entity("TestProject.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("TeacherID");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = 2,
                            Name = "Название Группы1",
                            Specialty = "Специальность1",
                            TeacherID = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            CourseID = 4,
                            Name = "Название Группы2",
                            Specialty = "Специальность2",
                            TeacherID = 3,
                            Year = 2018
                        });
                });

            modelBuilder.Entity("TestProject.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupID = 1,
                            Name = "Студент1",
                            PhoneNumber = 77836940,
                            Photo = "/img/Студент1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            GroupID = 1,
                            Name = "Студент2",
                            PhoneNumber = 77840182,
                            Photo = "/img/Студент2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            GroupID = 2,
                            Name = "Студент3",
                            PhoneNumber = 68593027,
                            Photo = "/img/Студент3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            GroupID = 2,
                            Name = "Студент5",
                            PhoneNumber = 77869104,
                            Photo = "/img/Студент5.jpg"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Имя1 Фамилия1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Имя2 Фамилия2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Имя3 Фамилия3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Имя4 Фамилия4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Имя5 Фамилия5"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Group", b =>
                {
                    b.HasOne("TestProject.Models.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.Teacher", "Teacher")
                        .WithMany("Groups")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TestProject.Models.Student", b =>
                {
                    b.HasOne("TestProject.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TestProject.Models.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TestProject.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("TestProject.Models.Teacher", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
